<?php

namespace NTI\NotificationBundle\Repository;
use NTI\NotificationBundle\Entity\Destination;

/**
 * DestinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinationRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param Destination $destination
     * @return array
     */
    public function getAvailableNotification(Destination $destination = null)
    {
        if (!$destination)
            return array();

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('destination')
            ->from('NotificationBundle:Destination', 'destination')
            ->leftJoin('destination.notification', 'notification')
            ->leftJoin('notification.status', 'nSts')
            ->leftJoin('destination.status', 'dSts')
            ->andWhere(
                $qb->expr()->eq('destination.destinationId', $qb->expr()->literal($destination->getDestinationId())),
                $qb->expr()->in('nSts.code', array('available','schedule')), # -- notification status
                $qb->expr()->in('dSts.code', array('read','unread')) # -- destination status
            )->orderBy('notification.scheduleDate', 'DESC');

        ;

        return $qb->getQuery()->getResult();
    }

    /**
     * @param string $destinationId
     * @return Destination|null
     */
    public function getOneByDestinationId(string $destinationId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('d')
            ->from('NotificationBundle:Destination', 'destination')
            ->andWhere(
                $qb->expr()->eq('destination.destinationId', $qb->expr()->literal($destinationId))
            )->setMaxResults(1)
        ;
        $result =  $qb->getQuery()->getResult();
        # -- get result returns an array
        if (sizeof($result) > 0) {
            /** @var Destination $destination */
            $destination = $result[0];
            return $destination;
        }
        return null;
    }
}
