<?php

namespace NTI\NotificationBundle\Repository;

/**
 * DestinationStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinationStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
