<?php

namespace NTI\NotificationBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{

    /**
     * external notifications from actives application
     * different from the default application.
     * @return array
     */
    public function getExternalNotifications()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('n')
            ->from('NotificationBundle:Notification', 'n')
            ->leftJoin('n.fromApplication', 'from_app')
            ->innerJoin('n.toApplication', 'to_app', Expr\Join::WITH,
                $qb->expr()->andX(
                    $qb->expr()->eq( 'to_app.isActive', true), # -- active applications
                    $qb->expr()->eq( 'to_app.isDefault', $qb->expr()->literal(false)), # -- exclude default application
                    $qb->expr()->isNotNull( 'to_app.requestKey'), # -- request key should not be null
                    $qb->expr()->neq('to_app.id', 'from_app.id')
                )
            )
        ->andWhere(
            $qb->expr()->in(array('pending','error'))
        )
        ;

        return $qb->getQuery()->getResult();
    }

}
